<!DOCTYPE bookstore SYSTEM "bookstore.dtd" [
    <!ELEMENT bookstore (book*)>
    <!ELEMENT book (title, author, price)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ATTLIST book
        id ID #REQUIRED
    >
]>
<bookstore>
    <book id="001">
        <title>The Catcher in the Rye</title>
        <author>J.D. Salinger</author>
        <price>10.99</price>
    </book>
    <book id="002">
        <title>To Kill a Mockingbird</title>
        <author>Harper Lee</author>
        <price>12.99</price>
    </book>
</bookstore>
